[package]
name = "comments"
version = "0.1.0"
authors = ["robert masen <r@robertmasen.pizza>"]

[dependencies]
# Here we're using a path dependency to use what's already in this repository,
# but you'd use the commented out version below if you're copying this into your
# project.
wasm-bindgen = { path = "../.." }
#wasm-bindgen = "0.2"

[lib]
crate-type = ['cdylib']